services:
  postgres:
    image: postgres:16-alpine
    container_name: neo-fala-amazonia-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: neo_fala_amazonia
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
